###################################################################################
## Guides - EXPERIMENTAL ##########################################################
###################################################################################

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  phpDocumentor\Guides\Graphs\Twig\UmlExtension: ~
  phpDocumentor\Guides\Graphs\Renderer\DiagramRenderer: '@phpDocumentor\Guides\Graphs\Renderer\PlantumlRenderer'

  phpDocumentor\Guides\Graphs\Renderer\PlantumlRenderer:
    arguments:
      $plantUmlBinaryPath: '%kernel.project_dir%/bin/plantuml'

  phpDocumentor\Pipeline\Stage\Parser\ParseGuides:
    tags:
      - { name: 'phpdoc.pipeline.api_documentation.parse', priority: 0 }

#  phpDocumentor\Pipeline\Stage\Cache\LoadGuidesFromCache:
#    tags:
#      - { name: 'phpdoc.pipeline.api_documentation.parse', priority: 2000 }
#      - { name: 'phpdoc.pipeline.api_documentation.transform', priority: 5000 }
#
#  phpDocumentor\Pipeline\Stage\Cache\StoreGuidesToCache:
#    tags:
#      - { name: 'phpdoc.pipeline.api_documentation.parse', priority: -1000 }
#
